# Generated by Django 6.0.6 on 2026-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaydalaniwshiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ati', models.CharField(max_length=100)),
                ('fm', models.CharField(max_length=100)),
            ],
        ),
    ]
